
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-web-ui
  namespace: keycloak
spec:
  rules:
  - host: keycloak.shaun.io
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-http
          servicePort: http