apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.5.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

    # - name: default
    # count: 3
    # config:
    #   node.master: true
    #   node.data: true
    #   node.ingest: true
    # podTemplate:
    #   spec:
    #     initContainers:
    #     - name: sysctl
    #       securityContext:
    #         privileged: true
    #       command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']