---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - port: 80
    name: web
    targetPort: "web"
  - port: 443
    name: websecure
    targetPort: "websecure"

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
  - port: 8080
    name: dashboard
    targetPort: "traefik"