
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik-config.yaml: |
    tls:
      stores:
        default: 
          defaultCertificate:
            certFile: /certs/tls.crt
            keyFile: /certs/tls.key
      certificates:
        - certFile: /certs/tls.crt
          keyFile: /certs/tls.key
          stores:
            - default